#pragma once

template <class T>
class CProxy_ITestComServerEvents : public IConnectionPointImpl<T, &__uuidof( _ITestComServerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
